### PR TITLE
Added CONTRIBTING.md and CODE_OF_CONDUCT.md file

### LINKED ISSUE #17: Add CONTRIBTING.md and CODE_OF_CONDUCT.md file
Add CONTRIBTING.md and CODE_OF_CONDUCT.md file

### PR DESCRIPTION
**Pull request by theritikchoure**
Fixed #17 

Add CONTRIBTING.md and CODE_OF_CONDUCT.md file

### CODE REVIEW

**Comment by warmachine028** [comment]
Check in hacktoberfest profile if this PR is showing in pending or not. So that I can accept it and you will get the hacktoberfest tag

**Comment by theritikchoure** [comment]
It is showing as not accepted.

Merge this pull request with ```hacktoberfest-accepted``` label

**Comment by warmachine028** [comment]
Good good. I will sccrp

**Comment by warmachine028** [comment]
Good Good! I will merge it

**Pull request merged**
