### PR TITLE
fixed demo section in documentation

### LINKED ISSUE #86: [DOCS 📄] Demo Section
### Description

Issued : the demo section of latest version of this repository doesn't show the gif.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rasvanjaya21**
# Issue #86 📐

- I am [@rasvanjaya21](https://github.com/rasvanjaya21) have worked for #86

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #86

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

memories-demo

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
- The new Demo looks good
- It is also under 20mb

However I can see in your branch that the demo is not previewing in README.md. 
- I would suggest you to directly upload this gif to the Readme as a Link 
- Rather than uploading as a file inside assets directory and relatively linking it.

**Comment by rasvanjaya21** [comment]
Yes sir, that's way we called it magic, I attach the link to your own [memories repository](https://github.com/warmachine028/memories) **directly** to avoid multiple PR. The link is excatly works and It will apply if you merge the PR.

**Comment by warmachine028** [comment]
Yes 

> Yes sir, that's way we called it magic, I attach the link to your own [memories repository](https://github.com/warmachine028/memories) **directly** to avoid multiple PR. The link is excatly works and It will apply if you merge the PR.

Yes let me merge it, I was thinking the same

**Comment by rasvanjaya21** [comment]
Thank you sir @warmachine028, happy to contribute 🎉

**Pull request merged**
