### PR TITLE
#79 bug Fixed :Outlines are not visible in dark mode are fixed

### LINKED ISSUE #79: [BUG 🐞] Outlines are not visible in dark mode
### Description

- The form outlines are not visible in dark mode for SignIn and SignUp forms
- Do not change anything for Default mode, only change it for Dark (Light)
- You can take reference from the Form.jsx component styles.

### Screenshots

Screenshot_2023-10-02-20-50-33-091_com android chrome

- Supposed to look similar to this 
Screenshot_2023-10-02-21-03-29-175_com android chrome

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by a-s-t-e-y-a**
# Issue #79 📐

- I <krishna seth](https://github.com/a-s-t-e-y-a) have worked for #79

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #79

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

image
  
  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
image

fix this for light mode. It should look like below
image

**Comment by a-s-t-e-y-a** [comment]
@warmachine028 okay I'll try to fix this

**Review by warmachine028 — CHANGES_REQUESTED** [review]
- This changes are still not like before in the light mode
- You can refer to the actual deployed site for the original view.

image

**Comment by a-s-t-e-y-a** [comment]
@warmachine028 Please review the latest commit again

**Comment by warmachine028** [comment]
> @warmachine028 Please review the latest commit again

## Perfect! You have solved a big issue. Merging it now

**Pull request merged**
