### PR TITLE
fix: updated regExptext instead of stringmatch and few anti pattern

### LINKED ISSUE #105: [BUG 🐞] recommended use of Prefer RegExptest() over Stringmatch()
### Description

Performance can be improved by using regexpTest() over Stringmatch()

### Screenshots

Screenshot 2023-10-05 at 11 03 34 PM

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by beneyalraj**
# Issue #105 📐

- I [abi beniyal](https://github.com/beneyalraj) have worked for #105 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #105 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

Screenshot 2023-10-05 at 11 45 19 PM
Screenshot 2023-10-07 at 10 30 40 PM
Screenshot 2023-10-07 at 10 29 03 PM
Screenshot 2023-10-07 at 10 28 53 PM
Screenshot 2023-10-07 at 10 28 40 PM
Screenshot 2023-10-07 at 10 28 30 PM
Screenshot 2023-10-07 at 10 28 12 PM
Screenshot 2023-10-07 at 10 28 05 PM
Screenshot 2023-10-07 at 10 27 58 PM
Screenshot 2023-10-07 at 10 27 49 PM
Screenshot 2023-10-07 at 10 27 39 PM

  
  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
- @beneyalraj well done in solving this bug, however I would recommend you to identify more such bugs and combine them into one single PR.
- Remember your contributions are bringing values to this project 🌟🌟

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Could you please explain the changes you made in 1 line each?

**Comment by beneyalraj** [comment]
yeah sure, 
I Have used regExptest() instead of stringmatch() in 1 file 
I have used strict equals instead of loose equals in 2 files
I Have used regular expression literal instead of the 'RegExp' constructor In 1 file  
I have used optional chain expression instead of logical and in 1 file 
I have changed local variable named which shadowed variables in outer scope in 4 files

**Comment by warmachine028** [comment]
Good, merging it to main

**Comment by beneyalraj** [comment]
thank you, will continue to contribute. can you please add the hacktoberfest-accepted label too?

**Comment by warmachine028** [comment]
Yes, I completely forgot it. Was preping for an interview, very busy.

**Pull request merged**
