### PR TITLE
Fixed tags input size

### LINKED ISSUE #97: [BUG 🐞] Tags Input field size incorrect when empty
### Description

The tags input field is in incorrect size when empty.

### Screenshots

image

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by Faisalhs51**
# Issue  #97  📐

- I [Faisal Husain Shaikh](https://github.com/Faisalhs51) have worked for #97 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #97 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

image

### CODE REVIEW

**Comment by Faisalhs51** [comment]
@warmachine028 Done ✅

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Screenshot_2023-10-04-21-09-48-486_com android chrome

The placeholder is "Tags" not "Search Tags"

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Screenshot_2023-10-04-21-13-52-410_com android chrome

The placeholder must not be visible if tag chips are already in the input


Screenshot_2023-10-04-21-15-52-089_com android chrome
 
Something like this, the placeholder becomes the label at the left corner, it is preferred

**Comment by warmachine028** [comment]
You have also changed the placeholder for Search component to Tags, it was alright "Search Tags" but only the Form component change was required

**Comment by Faisalhs51** [comment]
Done with the changes

**Review by warmachine028 — APPROVED** [review]
Screenshot_2023-10-04-21-49-59-993_com android chrome

**Pull request merged**
