### PR TITLE
fix: recover tab navigation functionality in user detail sections 

### LINKED ISSUE #100: [BUG 🐞] User attributes are not loading
### Description

- Only CREATED tab is loading
- CREATED, LIKED, PRIVATE, COMMENTS must start fetching once page loads 

### Screenshots

Screenshcom android chrome

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by cesardlinx**
# Issue #100 📐

- I [David Padilla](https://github.com/cesardlinx) have worked for #100

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #100

## Screenshots 📷

memories3

  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Page is crashing, check the logs

image

**Comment by warmachine028** [comment]
Alright, now push the changes

**Comment by cesardlinx** [comment]
I'm sorry, I don't think I explained myself well. What I'm trying to say is that those changes are already pushed, but it won't work if you don't install this new package. In other words you will have to run `npm install` again

**Comment by warmachine028** [comment]
image

check if the import statement is alright

**Comment by cesardlinx** [comment]
@warmachine028 ok I fixed the issue that I was having basically in the public profile, not sure if it was related with the crash that you're experiencing. About the import, yes for this library it has to be a default import instead of a named import as opposed to the previous package used. Check it out now, if it's not working on vercel try it out locally, let me know how it went

**Comment by warmachine028** [comment]
- Running Locally But the Liked posts are not fetching

image

- Please find some fix for the error online `Uncaught TypeError: Failed to resolve module specifier "@babel/runtime/helpers/createSuper". Relative references must start with either "/", "./", or "../".`
- I strongly belive it has something to do with the new library or something with package-lock.json with @babel package
- Also these warnings were generated while installing this new package

image

**Comment by cesardlinx** [comment]
Got it, yeah I agree it has to be something related with the new package. I'm going to do this, I'll test this on a linux computer, basically I'll try to reproduce the same error that you're having. I'll let you know how it went

**Comment by warmachine028** [comment]
Yes, I want to encourage you in making this PR successful because it is a very critical and vital issue you are working on

**Comment by cesardlinx** [comment]
@warmachine028 it works now! and with the previous library, give it a look

memories

**Review by warmachine028 — APPROVED** [review]
Well done @cesardlinx . Good to goh

**Pull request merged**
