### PR TITLE
Fix: Tags functionality readded

### LINKED ISSUE #82: [FEATURE 💡] Tags must be added
### Description

- have a look at this [previous deployment](https://memories-5xye0f5aj-warmachine028.vercel.app).
- Previously tags could be added in the Form by Chipinput.js
- Tags were searchable too.
- After migrating to MUI v5, we had to drop support for [mui-chip-input](https://www.npmjs.com/package/mui-chips-input).
- We used our own Component at Chipinput.js.
- But after migrating to Vite from CRA at #72 , we had to disable support for ChipInput.jsx
- Bring back this feature in the App, after using this feature carefully in the previous deployment.

### Screenshots

- Previously in Memories
image

- MUI Chip Input
image

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by Faisalhs51**
# Issue #82  📐

- I [Faisal Husain Shaikh](https://github.com/Faisalhs51) have worked for #82 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #82 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

image
    
---

image

---
image

### CODE REVIEW

**Comment by warmachine028** [comment]
Reviewing this 
Will be merging this in an hour

**Comment by warmachine028** [comment]
There is error in this Code, build is failing

**Comment by Faisalhs51** [comment]
please give me the Screenshot of the log message

**Comment by warmachine028** [comment]
First fix the PR template and remove the [ ] from the tile of the PR

**Review by warmachine028 — APPROVED** [review]
Changes LGTM for now, the size of the Tags input is not proper when empty. This will be resolved in a new issue. For now good job

**Pull request merged**
