### PR TITLE
 style title

### LINKED ISSUE #59: Mobile Responsiveness Issue
**Describe the bug**
When I see this beautiful website on a mobile device at 360px to read the whole post created by users I saw an insane thing the Post title is very big and looked very ugly and bad user experience

**To Reproduce**
1. Go to Mobile Screen 
2. Click on any post
3. Scroll down to the post title
4. See the error

**Expected behavior**
The title's font size should be small on mobile screens it looks awesome

**Screenshots**
Screenshot 2023-07-26 134821

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version 11

**Smartphone (please complete the following information):**
 - Device: Redmi 9 Prime
 - OS: Android
 - Browser Brave
 - Version 12

**Additional context**

### PR DESCRIPTION
**Pull request by 0rigin-c0de**
# Issue 59  📐

- I [Sunil Kumar](https://github.com/0rigin-c0de) have worked for #59 

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #59 

## Screenshots 📷

Here are the pictures of the changes that I have made 🔽

Screenshot 2023-07-26 235136

I have change font size and make it bolder to look attractive and style to italic 
  
  
  
---

### CODE REVIEW

**Comment by 0rigin-c0de** [comment]
I also want to change the scrollbar styles

**Comment by warmachine028** [comment]
## Congratulations 🎉 on your first contribution in Memories Project!

**Comment by 0rigin-c0de** [comment]
Thank you @warmachine028

**Comment by warmachine028** [comment]
Great work towards fixing that issue. However I would like to suggest some changes before merging this Pull Request.

- Could you please add a screenshot of desktop along with the mobile version.
- The tile now looks smaller than the message itself, make it a bit bigger
- Please remove the italics from the font, it seems not matching the overall content.
- I believe a use of breakpoints was important in this case as you were fixing the issue for mobile devices only

**Review by warmachine028 — CHANGES_REQUESTED** [review]
- I presume a proper use of breakpoint was necessary in this case since you were fixing the issue for mobile devices only. Apparantly the overall font size was edited instead, which would affect the rendering of fonts in devices where the font was correct initially.

**Comment by 0rigin-c0de** [comment]
I made the changes that you requested

This is desktop view
Screenshot 2023-07-27 013141

This is Mobile Veiw
Screenshot 2023-07-27 013226

**Comment by warmachine028** [comment]
Looks perfect! Great work ✨

**Comment by 0rigin-c0de** [comment]
I want to change the scrollbar style could you assign it to me

**Comment by warmachine028** [comment]
> I also want to change the scrollbar style could you assign it to me

Yes you can create a new issue for this and get assigned.

**Pull request merged**
