### PR TITLE
fixed duplicate module imports

### PR DESCRIPTION
**Pull request by beneyalraj**
# Issue #JS-0232 📐

- I abi beniyal https://github.com/beneyalraj have worked for #JS-0232

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #JS-0232

## Screenshots 📷

Here are the pictures of changes that I have 
Screenshot 2023-10-03 at 2 35 10 PM
made 🔽
Screenshot 2023-10-03 at 2 35 21 PM
Screenshot 2023-10-03 at 2 35 31 PM
Screenshot 2023-10-03 at 2 35 42 PM

  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
Please create an issue for this first to get assigned.

**Comment by beneyalraj** [comment]
> Please create an issue for this first to get assigned.
Bug fix. duplicate module imports.

**Comment by warmachine028** [comment]
- Identify more such anti-atterns in upcomming issues.
- Make sure to star this repo for more.

**Review by warmachine028 — APPROVED** [review]
Changes look alright

**Pull request merged**
