### PR TITLE
[Fixed-#52]: Added animation/transition in Mode Toggle Switch in Navb…

### LINKED ISSUE #52: [FEATURE] Animation in Theme toggle Button
### Description

- The theme toggle button in the application is currently generic and needs to be customized.
- It is requested to add a subtle animation that transitions from day to night when toggling the theme.
- The animation should provide a visually pleasing effect that enhances the user experience.
- The animation should be smooth and seamless, ensuring a gradual change in the appearance of the toggle button.
- The design and duration of the animation can be discussed and finalized in collaboration 

### Screenshots

- Something with a similar animation is expected
Day-Night-Toggle-with-Background-Animation

### Additional information

- The animation can be implemented using CSS transitions, animations.

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by avinasdube**
# Issue #52 📐

- I Avinash Dubey (@avinasdube) have worked for #52

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #52 

## NOTE : 

- Above changes do not apply to the Floating Navbar. I have tried my best to fix it but I couldn't. I suggest you to look into it before merging and if you can please fix it as you have access to further edit changes. I think the issue is with MUI Styled Components (maybe). Otherwise, merge it for now and create a new issue for the Floating Navbar Problem, and I'm also trying to fix it. If I find a solution, I'll fix it myself.

### CODE REVIEW

**Comment by warmachine028** [comment]
Please merge the latest changes in your branch, to update it. 
It was mentioned clearly in the [issue comment](https://github.com/warmachine028/memories/issues/52#issuecomment-1644282053).

> Just make sure to update your branch with the latest changes. I have made slight changes after the PR was merged.

This is causing the merge conflict.

**Comment by avinasdube** [comment]
Oh...sorry ! I did update but forgot to merge changes. I'll do it again and then make the PR.

**Comment by warmachine028** [comment]
I will have to resolve these merge conflicts, it will take some time

**Comment by warmachine028** [comment]
Great work on the animation part. I will be merging it soon!

> Above changes do not apply to the Floating Navbar. I have tried my best to fix it, but I couldn't. I suggest you look into it before merging and if you can please fix it as you have access to further edit changes. I think the issue is with MUI Styled Components (maybe). Otherwise, merge it for now and create a new issue for the Floating Navbar Problem, and I'm also trying to fix it. If I find a solution, I'll fix it myself.

- I believe it is enough work for one issue.
- The bug in the Floating navbar can be further fixed by creating a separate issue.

**Comment by avinasdube** [comment]
> Great work on the animation part. I will be merging it soon!
> 
> > Above changes do not apply to the Floating Navbar. I have tried my best to fix it, but I couldn't. I suggest you look into it before merging and if you can please fix it as you have access to further edit changes. I think the issue is with MUI Styled Components (maybe). Otherwise, merge it for now and create a new issue for the Floating Navbar Problem, and I'm also trying to fix it. If I find a solution, I'll fix it myself.
> 
> * I believe it is enough work for one issue.
> * The bug in the Floating navbar can be further fixed by creating a separate issue.

Thanks. I think simple animations are best instead of very fancy ones. I could have done more fancy but my "inner designer" 😄 wasn't allowing me to do so. So, I did the simple but beautiful one. And definitely create a new issue for the Floating Navbar problem. If I can't, then someone else would definitely do it.

**Comment by warmachine028** [comment]
Good news!🎊🎊🎊. I have fixed the issue with the animation in Floating Navbar

**Comment by avinasdube** [comment]
> Good news!🎊🎊🎊. I have fixed the issue with the animation in Floating Navbar. I will be pushing the updated code soon.

That's great. Thanks to you, I too got my very first badge on github for 2 PRs merged. 😍

**Pull request merged**
