### PR TITLE
fix: post updates doesn't clear form data

### LINKED ISSUE #73: [BUG 🐞] Post Updates Doesn't clear form data
### Description

- Post Updates keep form Data as Usual after updating.
- The clear Callback method must be invoked
- This callback method is passed with the update post dispatch event

### Screenshots

_No response_

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by abdulrehmanjaved-1**
# Issue #73 📐

-  abdulrehmanjaved-1 have worked for #73 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

## Issue to be closed 🛅

- My pull request closes #73

### CODE REVIEW

**Review by warmachine028 — APPROVED** [review]
Restore .env.example

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Restore .env.example file as before

**Comment by abdulrehmanjaved-1** [comment]
Glad to hear it

**Review by warmachine028 — APPROVED** [review]
Approved 🎉

**Comment by abdulrehmanjaved-1** [comment]
Everything correct now?

**Comment by warmachine028** [comment]
> Everything correct now?

Yes I have merged it and added hacktoberfest tags

**Pull request merged**
